repos:
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.11"
    hooks:
      - id: vulture
        args: ["data_cleaning_framework", "--ignore-names", "cls,cleaner,cleaners,validate_file_getter"]